name: Test

on:
  push:
    branches: [master]
    paths-ignore:
      - README.md
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-8]
        python-version: [3.6, 3.7, 3.8]
        include:
          - cxx: clang++-9
            python-version: 3.8
          - cxx: g++-9
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install FFmpeg and GTest
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libgtest-dev
      - name: Install PyTorch
        run: |
          pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install with CXX ${{ matrix.cxx }}
        run: |
          CXX=${{ matrix.cxx }} MAKEFLAGS="-j$(nproc)" python -m pip install --verbose --editable .
      - name: Test
        run: |
          python -m unittest --verbose
          $(find ./build -name videoloader_tests)

  cpp_only_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install FFmpeg and GTest
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libgtest-dev
      - name: Install with config ${{ matrix.config }}
        run: |
          mkdir build
          cd build
          cmake ../videoloader/_ext -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          make -j$(nproc)
      - name: Test
        run: |
          $(find ./build -name videoloader_tests)

  publish_sdist:
    needs: [build, cpp_only_build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Set up Enviroment
        run: pip install -U pip twine
      - name: Build sdist
        run: python setup.py sdist
      - name: publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
